# Generated by Django 2.2.3 on 2019-07-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/Y%/m%/d%/')),
                ('hire_date', models.DateField()),
            ],
            options={
                'ordering': ['-hire_date'],
            },
        ),
    ]
