# Generated by Django 2.2.3 on 2019-07-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='associated',
            field=models.ImageField(blank=True, upload_to='services/associated/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='service',
            name='in_img1',
            field=models.ImageField(blank=True, upload_to='services/in/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='service',
            name='in_img2',
            field=models.ImageField(blank=True, upload_to='services/in/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='service',
            name='in_img3',
            field=models.ImageField(blank=True, upload_to='services/in/%Y/%m/%d/'),
        ),
    ]
