# Generated by Django 2.2.3 on 2019-07-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Engineers',
            new_name='Engineer',
        ),
    ]
